ATSystem/Models/Entity/ProductCategory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ATSystem.Models.Entity
{
    public class ProductCategory
    {
        public int Id { set; get; }

        [DisplayName("Product Category Name")]
        [Required(ErrorMessage = "Product Category Required")]
        public string Name { set; get; }

        [DisplayName("Brand/Sub-Category")]
        [Required(ErrorMessage = "Brand Required")]
        public int BrandId { set; get; }

        public virtual Brand Brand { get; set; }

    }
}

ATSystem/Models/ViewModel/ProductCategory/ProductCategoryVM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using ATSystem.Models.Entity;

namespace ATSystem.Models.ViewModel.ProductCategory
{
    public class ProductCategoryVM
    {
        public int Id { set; get; }

        [DisplayName("Product Category Name")]
        [Required(ErrorMessage = "Product Category Required")]
        public string Name { set; get; }

        [DisplayName("Brand/Sub-Category")]
        [Required(ErrorMessage = "Brand Required")]
        public int BrandId { set; get; }

        public string Brand { get; set; }
    }
}

ATSystem/Controllers/BrandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ATSystem.Models.Entity;
using ATSystem.Models.Interface.BLL;
using ATSystem.Models.Interface.DAL;

namespace ATSystem.Controllers
{
    public class BrandController : Controller
    {
        private IBrandManager brandManager;
        private IGeneralCategoryManager generalCategoryManager;

        public BrandController(IBrandManager _brandManager,IGeneralCategoryManager _generalCategoryManager)
        {
            brandManager = _brandManager;
            generalCategoryManager = _generalCategoryManager;
        }
        
        public ActionResult Create()
        {
            if (Session["username"] == null)
            {
                return RedirectToAction("HomePage", "Home");
            }

            var brandtable = brandManager.GetSome(5);
            ViewBag.brandlist = brandtable.ToList();

            var list = generalCategoryManager.GetAll();
            ViewBag.orglist = list.ToList();
            bool s = Request.QueryString["success"] == "true";
            if (s)
            {
                ViewData["success"] = "Save Successfully";

            }
            return View();
        }

        [HttpPost]
        public ActionResult Create(Brand brand)
        {
            var brandtable = brandManager.GetSome(5);
            ViewBag.brandlist = brandtable.ToList();

            if (brandManager.Add(brand))
            {
                ModelState.Clear();
                return RedirectToAction("Create", new { success = "true" });
            }
            var list = generalCategoryManager.GetAll();
            ViewBag.orglist = list.ToList();
            return View(brand);
        }


        public JsonResult GetBrandssByCategoryId(int? categoryId)
        {
            var categories = brandManager.GetBrandssByCategoryId(categoryId).Select(c => new
            {
                c.Id,
                c.Name,
                c.Code,
                c.CategoryId,
                c.Description
            });
            return Json(categories, JsonRequestBehavior.AllowGet);
        }
    }
}

ATSystem/Controllers/ProductCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ATSystem.Models.Entity;
using ATSystem.Models.Interface.BLL;

namespace ATSystem.Controllers
{
    public class ProductCategoryController : Controller
    {
        private IProductCategoryManager productCategoryManager;
        private IGeneralCategoryManager generalCategoryManager;

        public ProductCategoryController(IProductCategoryManager _productCategoryManager,IGeneralCategoryManager _generalCategoryManager)
        {
            productCategoryManager = _productCategoryManager;
            generalCategoryManager = _generalCategoryManager;
        }


        public ActionResult Create()
        {
            if (Session["username"] == null)
            {
                return RedirectToAction("HomePage", "Home");
            }

            var productcategorylist = productCategoryManager.GetSome(5);
            ViewBag.plist = productcategorylist.ToList();

            var list = generalCategoryManager.GetAll();
            ViewBag.orglist = list.ToList();
            bool s = Request.QueryString["success"] == "true";
            if (s)
            {
                ViewData["success"] = "Save Successfully";

            }
            return View();
        }

        [HttpPost]
        public ActionResult Create(ProductCategory productCategory)
        {
            var productcategorylist = productCategoryManager.GetSome(5);
            ViewBag.plist = productcategorylist.ToList();

            var lists = generalCategoryManager.GetAll();
            ViewBag.orglist = lists.ToList();

            if (productCategoryManager.Add(productCategory))
            {
                ModelState.Clear();
                return RedirectToAction("Create", new { success = "true" });
            }
            var list = generalCategoryManager.GetAll();
            ViewBag.orglist = list.ToList();
            return View(productCategory);
        }
    }
}

ATSystem/Views/ProductCategory/Create.cshtml
@using ATSystem.Models.ViewModel.ProductCategory
@model ATSystem.Models.Entity.ProductCategory

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/MainPage.cshtml";
    List<ProductCategoryVM> alist = ViewBag.plist;
}

<div>
    @using (Html.BeginForm("Create", "ProductCategory", FormMethod.Post, new { id = "createform" }))
    {

        <div class="form-horizontal container">
            <div class="row">
                <br />
                <div class="col-md-8">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            Create Product Category
                        </div>
                        <div class="panel-body">
                            <div class="form-group col-md-12">

                                <br />
                                <div class="col-md-4">
                                    @Html.Label("General Category", new { @class = "control-label" })
                                </div>
                                <div class="col-md-8">
                                    @Html.DropDownList("GeneralCategoryId", new SelectList(ViewBag.orglist, "Id", "Code"), "Select...", new { @class = "form-control", Required = "required", title = "General Category Required" })
                                    @Html.ValidationMessage("GeneralCategoryId", new { style = "color:red;font-size:12px" })
                                </div>
                            </div>
                            <div class="form-group col-md-12">
                                <div class="col-md-4">
                                    @Html.Label("Category", new { @class = "control-label" })
                                </div>
                                <div class="col-md-8">
                                    @Html.DropDownList("CategoryId", new SelectList(new SelectListItem[] { new SelectListItem() { Value = "", Text = "Select..." } }, "Value", "Text"), new { @class = "form-control", Required = "required", title = "Category Required" })
                                    @Html.ValidationMessage("CategoryId", "", new { style = "color:red;font-size:12px" })
                                </div>
                            </div>
                            <div class="form-group col-md-12">
                                <div class="col-md-4">
                                    @Html.LabelFor(c => c.BrandId, new { @class = "control-label" })
                                </div>
                                <div class="col-md-8">
                                    @Html.DropDownListFor(c => c.BrandId, new SelectList(new SelectListItem[] { new SelectListItem() { Value = "", Text = "Select..." } }, "Value", "Text"), new { @class = "form-control" })
                                    @Html.ValidationMessageFor(c => c.BrandId, "", new { style = "color:red;font-size:12px" })
                                </div>
                            </div>
                            <div class="form-group col-md-12">
                                <div class="col-md-4">
                                    @Html.LabelFor(c => c.Name, new { @class = "control-label" })
                                </div>
                                <div class="col-md-8">
                                    @Html.TextBoxFor(c => c.Name, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(c => c.Name, "", new { style = "color:red;font-size:12px" })
                                </div>
                            </div>
                            <div class="form-group col-md-12">
                                <div class="col-md-9">
                                    @if ((string)ViewData["success"] == "Save Successfully")
                                    {
                                        <label class="alert alert-success pull-right" style="padding: 0px 70px; border: 3px solid transparent">@ViewData["success"]</label>
                                    }

                                </div>
                                <div class="col-md-3 btn-group">
                                    <input type="submit" value="Create" class="btn btn-success pull-right" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                
                
                <div class="col-md-4">
                    @if (alist.Count != 0)
                    {

                        <div class="panel panel-primary">
                            <div class="panel-heading">
                                Last 5 Added Organization
                            </div>
                            <div class="panel-body">
                                <table class="table table-striped table-responsive table-bordered">
                                    <thead class="head">
                                        <tr>
                                            <th>Product Name</th>
                                        </tr>
                                    </thead>
                                    @foreach (var list in alist)
                                    {
                                        <tr>
                                            <td>
                                                @list.Name
                                            </td>
                                        </tr>
                                    }

                                </table>

                                @*@Html.ActionLink("Back To List", "")*@
                            </div>
                        </div>
                    }
                </div>



            </div>
        </div>





        


    }
</div>



@section ProductCategoryCreateJS{

    <script type="text/javascript">
        $(document).ready(function() {
            $("#GeneralCategoryId").change(function() {
                //load relevant branches of organization
                var generalcategoryId = $("#GeneralCategoryId").val();

                var json = {
                    generalCategoryId: generalcategoryId
                };

                $.ajax(
                {
                    type: "POST",
                    url: '@Url.Action("GetCategoriesByGeneralCategoryId", "Category")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function(data) {

                        var blankOption = "<option value=''> Select...</option>";

                        $('#CategoryId').empty();
                        $('#CategoryId').append(blankOption);

                        $('#BrandId').empty();
                        $('#BrandId').append(blankOption);

                        
                        $.each(data,
                            function(key, value) {

                                var option = "<option value='" + value.Id + "'>" + value.Name + "</option>";
                                $('#CategoryId').append(option);

                            });

                    },
                    error: function(data) {

                    }
                });


            });
            $("#CategoryId").change(function() {
                //load relevant branches of organization
                var categoryId = $("#CategoryId").val();

                var json = {
                    categoryId: categoryId
                };

                $.ajax(
                {
                    type: "POST",
                    url: '@Url.Action("GetBrandssByCategoryId", "Brand")',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function(data) {

                        $('#BrandId').empty();
                        var blankOption = "<option value=''> Select...</option>";

                        $('#BrandId').append(blankOption);
                        $.each(data,
                            function(key, value) {

                                var option = "<option value='" + value.Id + "'>" + value.Name + "</option>";
                                $('#BrandId').append(option);

                            });

                    },
                    error: function(data) {

                    }
                });


            });





            



        });
    </script>

}