ATSystem/Models/Entity/AssetLocation.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ATSystem.Models.Entity
{
    public class AssetLocation
    {
        public int Id { get; set; }

        [DisplayName("Location Name")]
        [Required(ErrorMessage = "Location Name Required")]
        public string Name { get; set; }

        [DisplayName("Location Short Name")]
        [Required(ErrorMessage = "Location Short Name Required")]
        public string ShortName { get; set; }

        [DisplayName("Branch")]
        [Required]
        public int BranchId { get; set; }

        public virtual Branch Branch { get; set; }
    }
}

ATSystem/Controllers/AssetLocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using ATSystem.Models.Entity;
using ATSystem.Models.Interface.BLL;

namespace ATSystem.Controllers
{
    public class AssetLocationController : Controller
    {
        IAssetLocationManager assetLocationManager;
        IOrganizationManager organizationManager;

        public AssetLocationController(IAssetLocationManager _assetLocationManager, IOrganizationManager _organizationManager)
        {
            assetLocationManager = _assetLocationManager;
            organizationManager = _organizationManager;
        }

        public ActionResult Create()
        {

            var list = organizationManager.GetAll();
            ViewBag.orglist = list.ToList();
            bool s = Request.QueryString["success"] == "true";
            if (s)
            {
                ViewData["success"] = "Save Successfully";

            }
            return View();
        }
        [HttpPost]
        public ActionResult Create(AssetLocation assetLocation)
        {
            if (assetLocationManager.IsExist(assetLocation.ShortName))
            {
                ViewData["exist"] = "ShortName Already Exist";
                //var dr =Request.Form["OrganizationId"];
                
            }
            else
            {
                assetLocationManager.Add(assetLocation);
                ModelState.Clear();
                return RedirectToAction("Create", new { success = "true" });
            }

            
            var list = organizationManager.GetAll();
            ViewBag.orglist = list.ToList();
            return View(assetLocation);
        }
    }
}

ATSystem/Views/AssetLocation/Create.cshtml
@using System.ServiceModel.Channels
@using Newtonsoft.Json
@model ATSystem.Models.Entity.AssetLocation
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/MainPage.cshtml";
}

<div>
    @using (Html.BeginForm("Create", "AssetLocation", FormMethod.Post, new { id = "createform" }))
    {

        <div class="form-horizontal container">
            <div class="row">
                <br />
                <div class="col-md-12">
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                            Create Asset Location
                        </div>
                        <div class="panel-body">
                            <div class="col-md-12">
                                <div class="form-group col-md-12">
                                    <h4 align="center"><b>Create Asset Location</b></h4>
                                    <br />
                                    <div class="col-md-4">
                                        @Html.Label("Organization", new { @class = "control-label" })
                                    </div>
                                    <div class="col-md-8">
                                        @Html.DropDownList("OrganizationId", new SelectList(ViewBag.orglist, "Id", "Name"), "Select...", new { @class = "form-control", Required = "required", title = "Organization Required" })
                                        @Html.ValidationMessage("OrganizationId", new { style = "color:red;font-size:12px" })
                                    </div>
                                </div>
                                <div class="form-group col-md-12">
                                    <div class="col-md-4">
                                        @Html.Label("Branch", new { @class = "control-label" })
                                    </div>
                                    <div class="col-md-8">
                                        @Html.DropDownListFor(c => c.BranchId, new SelectList(new SelectListItem[] { new SelectListItem() { Value = "", Text = "Select..." } }, "Value", "Text"), new { @class = "form-control" })
                                        @Html.ValidationMessageFor(c => c.BranchId, "", new { style = "color:red;font-size:12px" })
                                    </div>
                                </div>
                                <div class="form-group col-md-12">
                                    <div class="col-md-4">
                                        @Html.LabelFor(c => c.Name, new { @class = "control-label" })
                                    </div>
                                    <div class="col-md-8">
                                        @Html.TextBoxFor(c => c.Name, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(c => c.Name, "", new { style = "color:red;font-size:12px" })
                                    </div>
                                </div>
                                <div class="form-group col-md-12">
                                    <div class="col-md-4">
                                        @Html.LabelFor(c => c.ShortName, new { @class = "control-label" })
                                    </div>
                                    <div class="col-md-8">
                                        @Html.TextBoxFor(c => c.ShortName, new { @class = "form-control" })
                                        @Html.ValidationMessageFor(c => c.ShortName, "", new { style = "color:red;font-size:12px" })
                                        <p class="text-danger" style="font-size: 12px">@ViewData["exist"]</p>
                                    </div>
                                </div>
                                <div class="form-group col-md-12">
                                    <div class="col-md-9">
                                        @if ((string)ViewData["success"] == "Save Successfully")
                                        {
                                            <label class="alert alert-success pull-right" style="padding: 0px 70px; border: 3px solid transparent">@ViewData["success"]</label>
                                        }

                                    </div>
                                    <div class="col-md-3 btn-group">
                                        <input type="submit" value="Create" class="btn btn-success pull-right" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>



@section AssetLocationCreateJS{

    <script type="text/javascript">
        $(document).ready(function () {
    $("#OrganizationId").change(function() {
        //load relevant branches of organization
        var organizationId = $("#OrganizationId").val();

        var json = {
             organizationId: organizationId
        };

        $.ajax(
            {
                type: "POST",
                url: '@Url.Action("GetBranchsByOrganizationId", "Branch")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(json),
                success: function (data) {

                    $('#BranchId').empty();
                    var blankOption = "<option value=''> Select...</option>";

                    $('#BranchId').append(blankOption);
                    $.each(data, function (key, value) {

                        var option = "<option value='" + value.Id + "'>" + value.Name + "</option>";
                        $('#BranchId').append(option);

                    });

                },
                error: function(data) {

                }
        });


    });



        
        });





    </script>

}