ATSystem/Models/Entity/Asset.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ATSystem.Models.Entity
{
    public class Asset
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string CodeWithPrefix { get; set; }
        public double Price { get; set; }
        public string SerialNo { get; set; }
        public string Description { get; set; }
        public int BrandId { get; set; }
        public virtual Brand Brand { get; set; }
        public bool Registered  { get; set; }
        public string Organization { get; set; }
    }
}

ATSystem/Models/ViewModel/Asset/AssetDetailsVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ATSystem.Models.ViewModel.Asset
{
    public class AssetDetailsVM
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public virtual string Code { get; set; }
        public double? Price { get; set; }
        public string SerialNo { get; set; }
        public string Description { get; set; }
        public string BrandName { get; set; }
    }
}

ATSystem/Models/ViewModel/Asset/AssetEntryVM.cs
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Web.Mvc;
using ATSystem.Models.Entity;

namespace ATSystem.Models.ViewModel.Asset
{
    public class AssetEntryVm
    {
        public int Id { get; set; }

        [Required]
        [Index(IsUnique = true)]
        //[Remote("IsNameExist", "Assets", ErrorMessage = "Name Already Exist.", AdditionalFields = "InitName")]
        public string Name { get; set; }

        [Required]
        [StringLength(6, MinimumLength = 3, ErrorMessage = "Code Must Be 3-6 Characters")]
        [Index(IsUnique = true)]
        //[Remote("IsCodeExist", "Assets", ErrorMessage = "Code Already Exist.", AdditionalFields = "InitCode")]
        public virtual string Code { get; set; }

        public string CodeWithPrefix { get; set; }

        [Required]
        public double? Price { get; set; }
        public string SerialNo { get; set; }
        public string Description { get; set; }
        public int GeneralCategoryId { get; set; }
        public string GeneralCategoryName { get; set; }
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public int BrandId { get; set; }
        public string BrandName { get; set; }
        public int ProductDetailsId { get; set; }
        public string Organiztion { get; set; }

        public Models.Entity.GeneralCategory GeneralCategory { get; set; }
        public Entity.Category Category { get; set; }
        public virtual Models.Entity.Brand Brand { get; set; }

        //public List<SelectListItem> GeneralCategoryLookUp { get; set; }
        //public List<SelectListItem> CategoryLookUp { get; set; }
        //public List<SelectListItem> SubCategoryLookUp { get; set; }
    }
}

ATSystem/Controllers/AssetController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Core.Metadata.Edm;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ATSystem.Models.Entity;
using ATSystem.Models.Interface.BLL;
using ATSystem.Models.ViewModel.Asset;
using ATSystem.Models.ViewModel.AssetRegistration;
using AutoMapper;

namespace ATSystem.Controllers
{
    public class AssetController : Controller
    {
        private IGeneralCategoryManager generalCategoryManager;
        private IAssetManager assetManager;
        private IBrandManager brandManager;
        private INewAssetManager newAssetManager;

        public AssetController(IGeneralCategoryManager _generalCategoryManager, IAssetManager _assetManager, IBrandManager _brandManager, INewAssetManager _newAssetManager)
        {
            generalCategoryManager = _generalCategoryManager;
            assetManager = _assetManager;
            brandManager = _brandManager;
            newAssetManager = _newAssetManager;
        }

        public ActionResult Entry()
        {
            if (Session["username"] == null)
            {
                return RedirectToAction("HomePage", "Home");
            }

            ViewBag.orglist = generalCategoryManager.GetAll();

            ViewBag.assetlist = assetManager.GetSome(5);
            bool s = Request.QueryString["success"] == "true";
            if (s)
            {
                ViewData["success"] = "Save Successfully";
            }
            
            return View();
        }

        [HttpPost]
        
        public ActionResult Entry(AssetEntryVm assetEntryVm)
        {
            ViewBag.orglist = generalCategoryManager.GetAll();

            ViewBag.assetlist = assetManager.GetSome(5);

            var assetCodeCheck=assetManager.GetAll().Where(c => c.Code == assetEntryVm.Code).ToList();

            if (!ModelState.IsValid)
            {
                return View(assetEntryVm);
            }
            else if (assetCodeCheck.Count > 0)
            {
                ViewBag.msg = "Code Already Exist";
                return View(assetEntryVm);
            }
            else
            {
                var assetEntry = Mapper.Map<Asset>(assetEntryVm);
                assetEntry.Registered = false;
                assetEntry.Organization = Session["organizationName"].ToString();
                assetManager.Add(assetEntry);

                //var newAssetEntry = Mapper.Map<NewAsset>(assetEntryVm);
                //newAssetManager.Add(newAssetEntry);

                ModelState.Clear();
                return RedirectToAction("Entry", new {success = "true"});
            }
        }

        // Edit Asset
        public ActionResult Edit(int? id)
        {
            if (Session["username"] == null)
            {
                return RedirectToAction("HomePage", "Home");
            }

            ViewBag.orglist = generalCategoryManager.GetAll();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Asset asset = assetManager.GetById(id);
            if (asset == null)
            {
                return HttpNotFound();
            }
            bool s = Request.QueryString["Update"] == "true";
            if (s)
            {
                ViewData["Update"] = "Update Successfully";

            }
            return View(asset);
        }

        [HttpPost]
        public ActionResult Edit(int? id, Asset asset)
        {
            ViewBag.orglist = generalCategoryManager.GetAll();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //Asset asset=new Asset();
            //asset.Code = assetvm.Code;
            //asset.Id = assetvm.Id;
            //asset.BrandId = assetvm.BrandId;
            if (assetManager.IsExistUpdate(asset.Code, id,asset.BrandId))
            {
                ViewData["exist"] = "Code Already Exist";
            }
            else
            {
                assetManager.Update(asset);
                return RedirectToAction("Edit", new { Update = "true" });
            }

            return View(asset);
        }


        public ActionResult Details(int? id)
        {


            if (Session["username"] == null)
            {
                return RedirectToAction("HomePage", "Home");
            }

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var result = from asset in assetManager.GetAll().Where(c => c.Id == id)
                join brand in brandManager.GetAll()
                on asset.BrandId equals brand.Id
                select new
                {
                    id = asset.Id,
                    name = asset.Name,
                    code = asset.Code,
                    price = asset.Price,
                    serialno = asset.SerialNo,
                    description = asset.Description,
                    brandname = brand.Name
                };
            AssetDetailsVM assetDetailsVm=new AssetDetailsVM();
            foreach (var t in result)
            {
                assetDetailsVm.Id = t.id;
                assetDetailsVm.Name = t.name;
                assetDetailsVm.Code = t.code;
                assetDetailsVm.Price = t.price;
                assetDetailsVm.SerialNo = t.serialno;
                assetDetailsVm.Description = t.description;
                assetDetailsVm.BrandName = t.brandname;
            }
            if (assetDetailsVm == null)
            {
                return HttpNotFound();
            }

            
            return View(assetDetailsVm);
        }




        public ActionResult AssetList()
        {
            if (Session["username"] == null)
            {
                return RedirectToAction("HomePage", "Home");
            }

            int id = Convert.ToInt32(Request.QueryString["delete"]);
            if (id != 0)
            {
                Asset asset = assetManager.GetById(id);
                assetManager.Delete(asset);
                return RedirectToAction("AssetList");
            }

            return View();
        }
        //Json Result Return AssetList

        public JsonResult GetAllAsset()
        {
            var totalRecord = assetManager.GetAllAssetWithGeneral_Category_SubCategory_Brand_Product(Session["organizationName"].ToString()).Count;
           
            var assetlist = assetManager.GetAllAssetWithGeneral_Category_SubCategory_Brand_Product(Session["organizationName"].ToString());

            //.OrderBy(sortColumn + " " + sortColumnDir)
            var assets = assetlist.Select(c => new
            {
                c.Id,
                c.SerialNo,
                c.Name,
                c.Code,
                c.Price,
                c.GeneralCategoryName,
                c.CategoryName,
                c.BrandName,
                c.Description
            });

            

            return Json(new{data=assets}, JsonRequestBehavior.AllowGet);
        }

        //Json Result Return Selected value list

        public JsonResult GetSelectedAllCategorybyid(int? id)
        {
            var Assetlistwithallcategorybyid =
                assetManager.GetAllAssetWithGeneral_Category_SubCategory_Brand_Product(Session["organizationName"].ToString())
                    .Where(c => c.Id == id)
                    .Select(c => new
                    {
                        c.GeneralCategoryId,
                        c.GeneralCategoryName,

                        c.CategoryId,
                        c.CategoryName,

                        c.BrandId,
                        c.BrandName

                    });
            return Json(Assetlistwithallcategorybyid, JsonRequestBehavior.AllowGet);
        }



    }
}

ATSystem/Controllers/BrandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ATSystem.Models.Entity;
using ATSystem.Models.Interface.BLL;
using ATSystem.Models.Interface.DAL;

namespace ATSystem.Controllers
{
    public class BrandController : Controller
    {
        private IBrandManager brandManager;
        private IGeneralCategoryManager generalCategoryManager;

        public BrandController(IBrandManager _brandManager,IGeneralCategoryManager _generalCategoryManager)
        {
            brandManager = _brandManager;
            generalCategoryManager = _generalCategoryManager;
        }
        
        public ActionResult Create()
        {
            if (Session["username"] == null)
            {
                return RedirectToAction("HomePage", "Home");
            }

            var brandtable = brandManager.GetSome(5);
            ViewBag.brandlist = brandtable.ToList();

            var list = generalCategoryManager.GetAll();
            ViewBag.orglist = list.ToList();
            bool s = Request.QueryString["success"] == "true";
            if (s)
            {
                ViewData["success"] = "Save Successfully";

            }
            return View();
        }

        [HttpPost]
        public ActionResult Create(Brand brand)
        {
            var brandtable = brandManager.GetSome(5);
            ViewBag.brandlist = brandtable.ToList();

            if (brandManager.Add(brand))
            {
                ModelState.Clear();
                return RedirectToAction("Create", new { success = "true" });
            }
            var list = generalCategoryManager.GetAll();
            ViewBag.orglist = list.ToList();
            return View(brand);
        }


        public JsonResult GetBrandssByCategoryId(int? categoryId)
        {
            var categories = brandManager.GetBrandssByCategoryId(categoryId).Select(c => new
            {
                c.Id,
                c.Name,
                c.Code,
                c.CategoryId,
                c.Description
            });
            return Json(categories, JsonRequestBehavior.AllowGet);
        }
    }
}

ATSystem/Views/Asset/Details.cshtml
@model ATSystem.Models.ViewModel.Asset.AssetDetailsVM
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/MainPage.cshtml";
}


<div class="container" >
    <div class="row" style="margin-top: 50px">
        <div class="col-md-6">
            <div class="row">
                <div class="col-md-4">
                    Name:
                </div>
                <div class="col-md-8">
                    @Model.Name
                </div>
            </div><br/>

            <div class="row">
                <div class="col-md-4">
                    Code:
                </div>
                <div class="col-md-8">
                    @Model.Code
                </div>
            </div><br />

            <div class="row">
                <div class="col-md-4">
                    Price:
                </div>
                <div class="col-md-8">
                    @Model.Price
                </div>
            </div><br />

            <div class="row">
                <div class="col-md-4">
                    Serial No:
                </div>
                <div class="col-md-8">
                    @Model.SerialNo
                </div>
            </div><br />

            <div class="row">
                <div class="col-md-4">
                    BrandName:
                </div>
                <div class="col-md-8">
                    @Model.BrandName
                </div>
            </div><br />
            @Html.ActionLink("Back To List","AssetList")
        </div>

        <div class="col-md-6">
            <div class="row">
                <div class="col-md-4">
                    Description:
                </div>
                <div class="col-md-8">
                    @Model.Description
                </div>
            </div>
        </div>
    </div>
</div>

ATSystem/Views/Asset/Edit.cshtml
@model ATSystem.Models.Entity.Asset

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/MainPage.cshtml";
}

@using (Html.BeginForm("Edit", "Asset", FormMethod.Post, new { id = "createform" }))
{
    <div class="form-horizontal">
        <div class="container">
            <br />
            <div class="panel panel-primary">
                <div class="panel-heading">
                    Create New Asset
                </div>
                <div class="panel-body">
                    <div class="alert alert alert-danger alert-dismissible fade in" role="alert" id="errorMsgForParts" style="display: none">
                        <strong>Sorry! </strong> This Parts Item Code Already Exist
                    </div>
                    <div class="col-md-6">
                        <div class="form-group ">
                            @Html.Label("General Category", new { @class = "col-md-4 control-label" })
                            <div class="col-md-8">
                                @Html.DropDownList("GeneralCategoryId", new SelectList(ViewBag.orglist, "Id", "Name"), "Select...", new { @class = "form-control", Required = "required", title = "General Category Required" })
                                @Html.ValidationMessage("GeneralCategoryId", new { style = "color:red;font-size:12px" })
                            </div>
                        </div>
                        <div class="form-group ">
                            @Html.Label("Category", new { @class = "col-md-4 control-label" })
                            <div class="col-md-8">
                                @Html.DropDownList("CategoryId", new SelectList(new SelectListItem[] { new SelectListItem() { Value = "", Text = "Select..." } }, "Value", "Text"), new { @class = "form-control", Required = "required", title = "Category Required" })
                                @Html.ValidationMessage("CategoryId", "", new { style = "color:red;font-size:12px" })
                            </div>
                        </div>
                        <div class="form-group ">
                            @Html.Label("Sub Category / Brand", new { @class = "col-md-4 control-label" })
                            <div class="col-md-8">
                                @Html.DropDownListFor(c => c.BrandId, new SelectList(new SelectListItem[] { new SelectListItem() { Value = "", Text = "Select..." } }, "Value", "Text"), new { @class = "form-control" })
                                @Html.ValidationMessageFor(c => c.BrandId, "", new { style = "color:red;font-size:12px" })
                            </div>
                        </div>
                        <div class="form-group ">
                            @Html.LabelFor(model => model.Code, "Code", new { @class = "col-md-4 control-label" })
                            <div class="col-md-8">
                                @Html.TextBoxFor(model => model.Code, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group ">
                            @Html.LabelFor(model => model.SerialNo, "Serial No", new { @class = "col-md-4 control-label" })
                            <div class="col-md-8">
                                @Html.TextBoxFor(model => model.SerialNo, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.SerialNo, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group ">
                            @Html.LabelFor(model => model.Name, "Name", new { @class = "col-md-4 control-label" })
                            <div class="col-md-8">
                                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group ">
                            @Html.LabelFor(model => model.Price, null, new { @class = "col-md-4 control-label" })
                            <div class="col-md-8">
                                @Html.TextBoxFor(model => model.Price, new { @class = "form-control" })
                                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Description, "Description", new { @class = "col-md-4 control-label" })
                            <div class="col-md-8">
                                <div class="input-group">
                                    @Html.TextAreaFor(model => model.Description, new { cols = 100, rows = 3, @class = "form-control", @style = "border-radius: 8px", PlaceHolder = "Description" })
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr />
                    <div class="col-md-12">
                        <div align="left" class="col-md-6">
                            @if ((string)ViewData["success"] == "Save Successfully")
                            {
                                <label class="alert alert-success pull-right" style="padding: 0px 70px; border: 3px solid transparent">@ViewData["success"]</label>
                            }
                        </div>
                        <div class="form-actions col-md-6" align="right">
                            <input type="submit" value="Update" class="btn btn-success" />
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@section AssetScriptJS{
    @*<script src="~/Scripts/Mine/AssetScript.js"></script>*@

    <script type="text/javascript">
        
$(document).ready(function () {
    var pathname = window.location.pathname.split("/");
    var filename = pathname[pathname.length - 1];
        //alert(filename);
        var json = {
            id: filename
        };
        $.ajax(
            {
                type: "POST",
                url: '@Url.Action("GetSelectedAllCategorybyid", "Asset")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(json),
                success: function (data) {
                    
                    //$('#GeneralCategoryId').empty();
                    $('#CategoryId').empty();
                    $('#BrandId').empty();
                    
                    $.each(data, function (key, value) {


                        //$('#GeneralCategoryId').val(value.generalCategoryId);
                        //$("#GeneralCategoryId option:selected").text(value.GeneralCategoryName);
                        //$("#GeneralCategoryId option:selected").remove();

                        $('#GeneralCategoryId').empty();
                        var generalcategoryoption = "<option value='" + value.generalCategoryId + "'>" + value.GeneralCategoryName + "</option>";
                        $('#GeneralCategoryId').append(generalcategoryoption);


                        //$('#CategoryId').val(value.CategoryId);
                        //$("#CategoryId option:selected").text(value.CategoryName);
                        //$("#CategoryId option:selected").remove();

                        var categoryoption = "<option value='" + value.CategoryId + "'>" + value.CategoryName + "</option>";
                        $('#CategoryId').append(categoryoption);

                        var brandoption = "<option value='" + value.BrandId + "'>" + value.BrandName + "</option>";
                        $('#BrandId').append(brandoption);

                        //$('#BrandId').val(value.BrandId);
                        //$("#BrandId option:selected").text(value.BrandName);
                        //$("#BrandId option:selected").remove();
                        

                    });

                },
                
            });


                });
       

        $("#GeneralCategoryId").change(function () {

            //load relevant branches of organization
            var generalcategoryId = $("#GeneralCategoryId").val();
            var json = {
                generalCategoryId: generalcategoryId
            };
            $.ajax(
            {
                type: "POST",
                url: '@Url.Action("GetCategoriesByGeneralCategoryId", "Category")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(json),
                success: function (data) {

                    $('#CategoryId').empty();
                    var blankOption = "<option value=''> Select...</option>";

                    $('#CategoryId').append(blankOption);
                    $.each(data, function (key, value) {

                        var option = "<option value='" + value.Id + "'>" + value.Name + "</option>";
                        $('#CategoryId').append(option);

                    });

                },
                error: function(data) {
                }
            });
        });

        $("#CategoryId").change(function() {
            //load relevant branches of organization
            var categoryId = $("#CategoryId").val();
            var json = {
                categoryId: categoryId
            };
            $.ajax(
            {
                type: "POST",
                url: '@Url.Action("GetBrandssByCategoryId", "Brand")',
                contentType: "application/json; charset=utf-8",
                data: JSON.stringify(json),
                success: function (data) {

                    $('#BrandId').empty();
                    var blankOption = "<option value=''> Select...</option>";

                    $('#BrandId').append(blankOption);
                    $.each(data, function (key, value) {

                        var option = "<option value='" + value.Id + "'>" + value.Name + "</option>";
                        $('#BrandId').append(option);
                    });
                },
                error: function(data) {
                }
            });
        });



    </script>
}